- bin/git-big-file
- bin/git-changes
> Fix env error on Linux Mint

- README.md
> Add gitbaby link.

- bin/git-nuke-untracked-files
Quick way to tidy your repository
> Add git-nuke-untracked files.

- bin/git-delete-tag
- bin/git-find-dirty
- bin/git-git
- bin/git-github-open
- bin/git-nuke
- bin/git-overwritten
- bin/git-prune-branches
- bin/git-rel
Clean up more shellcheck complaints raised by codeclimate
> Fix stuff caught by codeclimate

- bin/git-rebase-authors
- bin/git-rebase-work-in-progress
- bin/git-recently-checkedout-branches
- bin/git-rm-deleted-from-repo
- bin/git-show-overwritten
- bin/git-switch
- bin/git-track
More minor shellcheck fixes to chip away at the code climate errors.
> Clean more shellcheck complaints

- README.md
Fix copy-pasta error in star badge link.
> Fix copy-pasta error in star badge link

- README.md
- Add git-stashd to External Git Utilities
- Update git-follow description
> Add git-stashd to External Git Utilities

- bin/git-sp
- bin/git-undo-push
- bin/git-unpushed
- bin/git-unpushed-stat
- bin/git-when-merged
> Do more cleanups

- README.md
- bin/git-copy-branch-name
- bin/git-undelete
Add helper script to undelete a file.
> Add git-undelete script

- bin/git-taglist
Somehow forgot to merge this to the public repo
> Add git-taglist

- bin/git-history-eraser
Add script to remove a file from the git history
> Add git-history-eraser

- README.md
Added link to article about reviewing messy merge commits.
> Add link to article about how to review merges

- README.md
Add link to [git-cop](https://github.com/bkuhlmann/git-cop).
> Add git cop

- README.md
* Minor wording and formatting tweaks throughout
* Add link to Marcus' blog post
> Add linear history article

- .travis.yml
- README.md
Add tip for rewriting git@ remote urls to https:// or ssh://
> Add misc tips section, start with automatic url rewriting

- README.md
Add link to [Git Submodules Revisted](https://dev.to/dwd/git-submodules-revisited-1p54) article.
> Add link to Dave Cridland's submodules article

- CodeOfConduct.md
> Update the Code of Conduct

- README.md
Add link to [Top ten pull request review mistakes](https://blog.scottnonnenberg.com/top-ten-pull-request-review-mistakes/) article
> Add Scott Nonnenberg's excellent article on PR review mistakes

- Contributing.md
- README.md
* Wording tweaks in README.md
* Update instructions in Contributing.md
> Update readme text

- README.md
Add link to [gitgo](gitgo](https://github.com/ltj/gitgo)
> Add link to gitgo

- README.md
- bin/git-current-branch
- git-extra-commands.plugin.zsh
* Add `git-current-branch` script and a completion entry for it
> Add `git-current-branch` script

- README.md
* Add link to [commit-helper](https://github.com/andre-filho/commit-helper) tool
> Add link to commit-helper tool

- README.md
- bin/git-tag-and-sign
* Add helper script to create and sign a new tag
> Add helper script to create and sign a new tag

- README.md
Add some missing prerequisites
Based on she-bang lines from files in the `/bin` folder, add some interpreters/programs that are required for various commands.
> List additional prerequisites

- .circleci/config.yml
- .travis.yml
- README.md
> Switch from travis to circleci

- README.md
Steve Lorek's blog has gone 404
> Steve Lorek's blog has gone 404

- README.md
Add link to Neil's github page
> Add link to Neil's github page

- README.md
Add link to git-rebase.io tutorial
> Add link to git-rebase.io tutorial

- README.md
* Add _More Productive Git_ article link
> Add _More Productive Git_ article link

- README.md
- bin/git-branch-name
- git-extra-commands.plugin.zsh
* Add `git-branch-name` script
> Add git-branch-name

- README.md
> Add link to hitch

- README.md
* Clarify non-framework usage instructions
> Clarify non-framework usage instructions

- README.md
- bin/git-up-old
- bin/git-what-the-hell-just-happened
* List framework instructions in order of usefulness (speed + usability) and update TOC accordingly
* Clean up formatting of git -> `git` for consistency
* Add link to  Patrick Porto's [4 Branching Workflows for git](https://medium.com/@patrickporto/4-branching-workflows-for-git-30d0aaee7bf) article
* Minor `spellcheck` fixes
> Reorganize frameworks instructions and add workflows article

- Contributing.md
- PULL_REQUEST_TEMPLATE.md
- git-extra-commands.plugin.zsh
* Add `cd-gitroot` alias
* Clarify new script policy in [Contributing.md](https://github.com/unixorn/git-extra-commands/blob/master/Contributing.md)
* Add checklist item that new scripts do not have language extensions in their names to PR template
> Administrivia

- README.md
- [*] All new and existing tests pass.
- [*] I have read the **CONTRIBUTING** document.
- [*] This repository is Apache version 2.0 licensed (some scripts may have alternate licensing inline in their code) and by making this PR, I am contributing my changes to the repository under the terms of the Apache 2 license.
> Add tip about setting git autocorrect

- README.md
Add link to switch-git plugin now that https://github.com/robin-mbg/switch-git/issues/1 is closed.
> Add switch-git ZSH plugin

- .circleci/config.yml
We were getting false negatives during awesome-zsh-plugins repo checks because github was refusing connections once we hit their rate limits.
Pre-emptively add ` --request-delay 1` to the `awesome_bot` check in circleci to prevent that from happening here too.
> Pause 1 second between URL validation probes

- README.md
- bin/git-branches
- bin/git-history-graph
- bin/git-ref-recent
- bin/git-stashes
- bin/git-tags
* Add `git-ref-recent` and `git-history-graph`
* Add `git-branches`, `git-stashes` and `git-tags` pluralizer scripts.
> Add more commands

- bin/git-stashes
- bin/git-tags
- git-tags: Missing dash in `list` flag
- git-stashes: `lists` should be `list`
> Fix two typos from #117

- README.md
- bin/git-checkout-pr
> Add git-checkout-pr script

- PULL_REQUEST_TEMPLATE.md
- README.md
* Add link to Git Koans article
* Remove trailing slash from PR template
> Add link to Git Koans article

- bin/git-add-username-remote
> Fix script name in help

- README.md
* Add thanks section
* Add howto for finding default branch when it is not `master`
> Add thanks

- README.md
- bin/git-trail
Corrected Leah's name in `git-trail` script and readme credits.
> Corrected Leah's name in script and credits.

- README.md
- bin/git-sr
> Add nil's git-sr script

- README.md
- bin/git-sr
Update Noel's git-sr to the new ruby version
> Update Noel's git-sr to the new ruby version

- README.md
- bin/git-attic
- bin/git-comma
- bin/git-neck
- bin/git-trail
Some old stuff had incorrect attribution to Leah's work, so fix the
attribution for those scripts (namely attic, neck, and trail). All of
the links now use HTTPS as well, though that's not required.
> Fix author credits for Leah Neukirchen

- bin/git-wordiness
- git-extra-commands.plugin.zsh
Add the missing git-wordiness script.
> Add missing git-wordiness script

- README.md
Add link to the gunstage repo which provides a `git unstage` command
> Add link to gunstage

- .github/workflows/awesomebot.yml
- .github/workflows/superlinter.yml
- README.md
* Add superlinter Github action
* Replace circleci link check with Awesomebot Github action
* Update badges to have Github status instead of circleci
> Add superlinter

- README.md
- bin/git-functionlog
Add a `git-functionlog` script to allow you to get logs for a specific function in a file instead of the whole file.
Based on discussion on tgamblin's tweet https://twitter.com/tgamblin/status/1340834896432926720
> Add git-functionlog

- README.md
Add link to Susan Potter's excellent article about how to get function-specific `git` logs
> Add link to Susan Potter's post about git diff

- README.md
Add link to [A Thorough Introduction to Git's Interactive Patch Mode](https://dev.to/krnsk0/a-thorough-introduction-to-git-s-interactive-patch-mode-4bl6) post about interactive patching
> Add link to blog post about interactive patching

- README.md
Add link to [igit](https://github.com/ytakahashi/igit)
> Add link to igit

- README.md
Make things look consistent by replacing git with `git` in readme
> Replace git with `git` in a bunch of places I missed

- README.md
* A few more git -> `git`
* Zsh -> ZSH
* Added some links to programs referenced
> More formatting changes

- README.md
Add link to flowr git-flow plugin
> Add link to flowr git-flow plugin

- README.md
- bin/git-fetch-prs
Adds `git-fetch-prs` script that gets all Pull Request branches as local remote branches by refspec.
> Add git-fetch-prs script

- README.md
- bin/git-oldest-common-ancestor
> Add git-oldest-common-ancestor script

- README.md
- bin/git-undo
`git-undo` undoes your last commit without discarding the changes.
> Add git-undo

- README.md
- bin/git-recent
`git-recent` shows the summary of the most recent commit on all local branches.
> Add git-recent script

- README.md
> Fix sort in script list

- README.md
- Add link to `gig` generator for `.gitignore` files
> Add link to gig

- README.md
- bin/git-checkout-commit
- bin/git-checkout-preview
- bin/git-commit-browser
- bin/git-fzf-add
Add a bunch of helper scripts that use fzf to select branches or commits.
- Add `git-checkout-preview` - Use `fzf` to select a branch and show preview of the diffs between it and your branch
- Add `git-commit-browser` - Use `fzf` to select commits from repo history
- Add `git-checkout-commit` - Use `fzf` to rummage through the commit history and check out a past commit
> Add more fzf functions

- README.md
- Fixed a few entries in the included scripts, where both description and original source, were merged together in a single section of the table.
> Fixed description for FZF wiki

- bin/git-checkout-default-branch
> Fix missing -

- README.md
- Add link to [worktree](https://github.com/jspears/worktree)
> Add worktree plugin

- README.md
> Add git-fuzzy plugin

- README.md
Mark Nielsen wrote a good blog post showing how to use [fzf](https://github.com/junegunn/fzf) for `git` checkouts. Add a link to it.
> Add link to Mark Nielsen's fuzzy git checkout blog post

- README.md
- bin/git-delete-dangling-commits
Add `git-delete-dangling-commits` script that deletes any commits that are not on a branch.
> Add git-delete-dangling-commits

- README.md
- Add link to Marcus Crane's blog post
- Sort fix for external utility list
> Add link to conditional .gitconfig blog post

- Contributing.md
- README.md
- bin/git-branch-rebaser
- bin/git-checkout-by-date
- bin/git-unpushed
- bin/git-unreleased
Add git-checkout-by-date script
> Add git-checkout-by-date script

- README.md
> Add git-children-of script

- README.md
- bin/git-tag-diff
Add John Wiegley's `git-tag-diff` script
> Add John Wiegley's git-tag-diff script

- .github/workflows/awesomebot.yml
- README.md
- Add status badge for awesomebot github action
- Add status badge for superlinter github action
> Add awesomebot and superlinter status badges

- README.md
- bin/git-files
- bin/git-stats
- Add `git-files` and `git-stats` scripts
- Bugfix in `git-origin-head` script
> Add `git-files` and `git-stats` scripts

- .github/workflows/superlinter.yml
Update superlinter configuration to @v4
> Update superlinter configuration to @v4

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/superlinter.yml
Update the superlinter configuration after renaming the default branch to main.
> Update superlinter after renaming master to main

- README.md
Add link to git-worktree ZSH plugin
> Add link to git-worktree ZSH plugin

- .github/workflows/awesomebot.yml
I'd rather have a false pass than have a PR fail checks because a server is overloaded.
> Make awesomebot ignore more 5?? error codes

- README.md
- bin/git-ls-branch-files
- bin/git-ls-conflicts
> Add git-ls-branch-files

- README.md
> Update oh-my-zsh link

- .github/workflows/mega-linter.yml
Switch to mega-linter. Disable cspell because it tries to spellcheck yaml files.
> Switch to mega-linter

- README.md
- Add link to [more-hooks-for-git](https://github.com/capsulescodes/more-hooks-for-git) ZSH plugin
> Add more-hooks-for-git

- README.md
- bin/git-fetch-prs
- bin/git-pr-fetch
- Allow specifying a remote to fetch the PRs from instead of only origin
- Add `--help`
- Add check that `git` is in your `$PATH`
> Update fetch prs

- bin/git-churn
> Reformat `git-churn`

- .codeclimate.yml
- .github/PULL_REQUEST_TEMPLATE.md
Update deprecated codeclimate settings.
> Update codeclimate configuration

- README.md
- bin/git-jump
- Add `git-jump` script
- Fix markdown warning in readme
-
> Add `git-jump` script

- README.md
Add link to **Learn Git Branching** tutorial
> Add link to "Learn Git Branching" tutorial

- README.md
- bin/git-superpull
Add `git-superpull` helper script
> Add `git-superpull` helper script

- .github/workflows/awesomebot.yml
- .github/workflows/mega-linter.yml
- README.md
Clean up markdown list formatting in readme
> Markdown cleanups

- README.md
- bin/git-side-by-side
`git-side-by-side` does command line side by side diffs similar to github PRs.
> Add `git-side-by-side` script

- README.md
> Add link to git-activity

- README.md
- bin/git-make-gitignore
`git-make-gitignore` prints language-specific `.gitignore` files.
> Add `git-make-gitignore` script

- README.md
- bin/git-pr-list
- Add `git-pr-list` command
- Add readme entry for `git-pr-fetch` command
> Add `git-pr-list` command

- README.md
- bin/git-delete-remote-branch
`git-delete-remote-branch` deletes a branch from a remote.
> Add `git-delete-remote-branch` helper script

- README.md
- bin/git-replace-author
`git-replace-author` uses `git-filter-branch` to rewrite all commits with one name to use another.
> Add `git-replace-author`

- README.md
Clean up `fig` entry and update TOC.
> Clean up `fig` entry

- README.md
- bin/git-release-tag
Add another of Mislav's `git` scripts.
> Add `git-release-tag`

- .github/FUNDING.yml
- .github/workflows/awesomebot.yml
- .github/workflows/mega-linter.yml
Signed-off-by: Joe Block <jpb@unixorn.net>
- Update mega-linter GitHub action to v6
> Update mega-linter to v6

- README.md
Shows five different Git workflows and the way they tackle various aspects of code collaboration: introducing changes, solving conflicts, using branches, and more.
> Add link to workflows article

- README.md
- bin/git-log-single-file
Add `git-log-single-file` that shows log messages for a single file.
> Add `git-log-single-file`

- .github/PULL_REQUEST_TEMPLATE.md
Move license acceptance to the top of PR template
> Move license acceptance to the top of PR template

- README.md
Signed-off-by: Joe Block <jpb@unixorn.net>
- Add a link to Platform Specfic Gitconfigs blog post
> Add a link to Platform Specfic Gitconfigs blog post

- README.md
Make all the list entries in the articles section consistent, and sort them into alphabetical order instead of just tacking stuff onto the end.
> Make the articles section more consistent

- README.md
Antigen doesn't cope when the default branch of a repo is not named `master` - see https://github.com/zsh-users/antigen/issues/717
Update the install instructions in the readme accordingly.
> Update antigen install instructions.

- README.md
- bin/git-branch-diff
Add `git-branch-diff` from hangops
> Add `git-branch-diff` helper

- README.md
- bin/git-open-jira
Signed-off-by: Joe Block <jpb@unixorn.net>
Add `git-open-jira` script. If your git branch starts with `JIRAPROJECT-NNNN-`, `git-open-jira` finds the associated Jira ticket and opens it.
macOS only for now.
> Add `git-open-jira`

- README.md
- bin/git-branch-date
Add `git-branch-date` per hangops post
> Add `git-branch-date`

- .github/workflows/dependabot.yml
> Add dependabot GH action

- README.md
Remove link to http://stevelosh.com/blog/2013/04/git-koans, no longer answering TCP
> stevelosh.com is not answering TCP

- README.md
- Re-add git koans now that stevelosh.com is responding again
- Sort fixes
> Re-add git koans now that stevelosh.com is responding again

- README.md
Can't open tcp connection to firstaidgit.io
> Can't open tcp connection to firstaidgit.io

- README.md
stevelosh.com isn't allowing tcp connections, remove
> stevelosh.com isn't allowing tcp connections, remove

- bin/git-branch-name
- git-extra-commands.plugin.zsh
Add more completions `definitions`
> Add more completion definitions

- .github/workflows/awesomebot.yml
- README.md
- bin/git-branch-clean
- bin/git-brcl
- bin/git-capture-wip
> Add @Hefeweizen's git scripts

- README.md
- The main fig link works, but the one to this project is 404. I'd try to fix it there, but their site wants to rummage through all my github organizations and I'm unwilling to grant it that access.
> Fig link is 404, remove

- git-extra-commands.plugin.zsh
Use more efficient path manipulation
> Use more efficient path manipulation

- README.md
Fix the inconsistent entries in the script list table in README.
> Clean up script list table

- bin/git-add-username-remote
- bin/git-branches-that-touch
- bin/git-merged-branches
- bin/git-release-tag
- bin/git-remove-conflicts
- bin/git-tag-diff
- bin/git-where-pr
As mentioned in this template and in `CONTRIBUTING.md`, shebangs must be in the style of  `#!/usr/bin/env interpreter`. This fixes that for older Bash scripts (that may have been added before this policy).
> fix: Remove remaining `#!/bin/bash` shebangs

- README.md
This updates `README.md`'s table of contents with [doctoc](https://github.com/thlorenz/doctoc).
> readme: Remove missing section from TOC

- .github/workflows/pre-commit.yml
- .pre-commit-config.yaml
> Add more pre-commit checks

- README.md
Add link to jevans miscellaneous `git` facts post
> Add jevans miscellaneous git facts link

- README.md
Add link to `git` bisect intro blog post
> Add link to `git` bisect intro blog post

- bin/git-branch-diff
- bin/git-branch-status
- bin/git-brcl
- bin/git-capture-wip
- bin/git-jump
- bin/git-merged-branches
- bin/git-move-commits
- bin/git-open-jira
- bin/git-remove-conflicts
- bin/git-replace-author
- bin/git-superpull
- bin/git-trail
- bin/git-undo-push
- bin/git-unreleased
- bin/git-up-old
- bin/git-upstream-sync
- bin/git-where
- bin/git-winner
These changes generally improve quoting:
- Where Git usually accepts a "sha1", it really accepts a "refspec". These can contain whitespace.
- Other quoting improvements (shellcheck, etc.)
> Improve quoting of shell variables

- .github/PULL_REQUEST_TEMPLATE.md
- README.md
Add link to Julia Evans' latest git rebase blog post
> Add Julia Evans' latest git rebase blog post

- README.md
Add link to https://moxio.com/blog/ignoring-bulk-change-commits-with-git-blame/#git-2.23-to-the-rescue
> Add link to `git blame` article

- .github/workflows/awesomebot.yml
On top of paywalling articles seemingly at random, occasionally it 429s valid links.
> Whitelist medium.com

- README.md
- Add link to darrenburns/dunk, a diff prettifier.
> Add link to dunk

- README.md
Replace git-rebase.today link with archive.is link
> Replace git-rebase.io link

- README.md
- bin/git-submodule-ls
- bin/git-submodule-paths
- Add `git-submodule-ls`
- Add `git-submodule-paths`
> Add more submodule tools

- README.md
> Forgot to commit readme tweak

- README.md
opensource.org moved their license files again, update link
> Update link to license file

- .github/workflows/awesomebot.yml
Make `awesomebot` ignore `202`s
> Update awesomebot config

- README.md
- Added link to https://jordanelver.co.uk/blog/2020/06/04/fixing-commits-with-git-commit-fixup-and-git-rebase-autosquash/
- Fixed sort in article section
> Added a link to article on fixup commits

- bin/git-upstream-sync
- Improve default remote detection in `git-upstream-sync`
> Improve default remote detection
