unixorn/git-extra-commands

bin/git-shamend

Update git-shamend with more of Danielle's changes

---

.travis.yml
README.md

Improving my git workflow doesn't look like its ever coming back, so get
rid of the temporary whitelisting
Closes #6

Remove link to blog post that has gone 404

---

README.md

Add descriptions to all the scrips.
Closes #7

Convert credits to table

---

README.md
bin/git-sp
git-extra-commands.plugin.zsh

Heres a script I've been tinkering with for a while. I didn't see anything like it on your list so I figured I'd see if I could add it.
Thanks.

Added git-sp

---

README.md

* add `git fetch-pull-requests`
* add `git roots`
* add `git unpushed`

Add some more useful git aliases to the readme

---

bin/git-comma
bin/git-ignored
bin/git-nuke-untracked-files
bin/git-purge-from-history
bin/git-root-directory
bin/git-submodule-rm
bin/git-upstream-sync

* Make `git-root-directory`, `git-ignored` and `git-nuke-untracked-files` return useful exit codes
* Clean quoting; remove extra space in command
* Quote bare variables in git-comma
* Update doc in git-upstream-sync

Clean up docs

---

README.md
bin/git-diff-last

Added [git-diff-last](https://github.com/sschuberth/dev-scripts/blob/master/git/git-diff-last.sh)

Add git-diff-last

---

bin/git-upstream-sync

Make `git-upstream-sync` read the upstream remote with `git config` and default to using
upstream if that is unset.

Make git-upstream-sync use a configurable remote

---

README.md

Add link to [“Git” it together: Some tips on commit etiquette and best practices for junior developers](https://hackernoon.com/git-it-together-some-tips-on-commit-etiquette-and-best-practices-for-junior-developers-1f147b8dfd56)

Add link to git commit message article

---

README.md

Add link to [mergepbx](https://github.com/simonwagner/mergepbx)

add link to mergepbx

---

README.md

Add [git-extend](https://github.com/nickolasburr/git-extend) link to External Git Utilities section.

Add git-extend link to External Git Utilities

---

README.md
bin/git-rename-branches

* Add Mestrelion's branch renamer script

Add Mestrelion's branch renamer script

---

bin/git-cut-branch

`git branch` no longer uses `--set-upstream`, so updated `git-cut-branch` to use `--set-upstream-to` instead.

Update cut branch

---

PULL_REQUEST_TEMPLATE.md
README.md
git-extra-commands.plugin.zsh

Minor cleanups

---

.travis.yml
PULL_REQUEST_TEMPLATE.md

Add license acceptance to PR template

Add license acceptance to PR template

---

README.md

Add link to [git-complete-urls](https://github.com/rapgenic/zsh-git-complete-urls), a ZSH plugin to enhance git completion to include in the remotes completion (e.g. from `git clone`) any URL in the clipboard.

Add link to git-complete-urls ZSH plugin

---

git-extra-commands.plugin.zsh

You are missing a backslash end of line 32

add missing backslah

---

README.md

Fix gitgo link

---

README.md

`git-forest` requires that `Git.pm` be installed. Closes #92

List git-forest dependencies in Readme

---

README.md
bin/git-gitlab-mr

Add @nilium's `git-gitlab-mr` and `git-wordiness` scripts

Add gitlab mr

---

README.md

Move install instructions after list of included scripts

Re-order README.md sections

---

README.md
bin/git-branch-rebaser

Add @karthikRangaraju's git-branch-rebaser script

---

README.md
bin/git-lines

Add Neil's git-lines script

---

README.md
bin/git-submodule-rm

The existing version of `submodule-rm` didn't remove the data in `.git/modules`. It also failed when running in an unclean git directory.
This PR replaces most of the script, but I left the credit to Greg V in the script because it still contains some of the original work.
Note that this PR also changes the interpreter from zsh to bash.

Fix submodule-rm script

---

bin/git-delete-local-merged
bin/git-delete-merged-branches

This fixes commands `delete-local-merged` and `delete-merged-branches` in case of having several working trees with different branches checked out.
`git branch` prepends checked out branches not only with `*`, but also with `+` if they're checked out in another working trees:
```
$ git branch
+ feature/something-something
* master
refactoring/something-else
```
Using `delete-local-merged` produces errors in such case:
```
$ git delete-local-merged
error: branch '+' not found.
error: Cannot delete branch 'feature/something-something' checked out at '/path-to-the-repo'
```

Fix filtering out checked out branches

---

README.md
bin/git-switch-branch

Rename `git-switch` to `git-switch-branch` now that git 2.23 added a `git-switch` in core
It now also only looks at the first match in cases where there are multiple matching branches so that it won't fail.
Closes https://github.com/unixorn/git-extra-commands/issues/119

Rename git-switch to git-switch-branch

---

bin/git-delete-local-merged

`git-delete-merged-branches` and `git-delete-local-merged` both do the same thing, but `git-delete-merged-branches` works better. Get rid of `git-delete-local-merged`, but make it a symlink to `git-delete-merged-branches` so we don't break people's workflows.

No need for both scripts

---

bin/git-current-branch

`git-current-branch` is basically the same as `git-branch-name`, but without trimming the whitespace.
Make it a symlink to `git-branch-name` so removing it doesn't break people's scripts.
Closes #122

git-current-branch was redundant, replace with symlink

---

bin/git-edit-conflicts

The command roughly boiled down to `git diff --name-only | uniq`, which isn't specific to just conflicted files.  It works if run when first entering a conflicted state, but if you unstage any changes it'll cause some issues.  More to the point, if run when *not* in a conflicted state, it would just open any unstaged changes, since it's just looking for unstaged changes.  We already have a good script for listing files in a conflict state ([`git-conflicts`](https://github.com/unixorn/git-extra-commands/blob/cc3d4f2d3a8718bfa7bf902ae296f31ebca50a5c/bin/git-conflicts), which runs `git ls-files -u | awk '{print $4}' | sort -u`), which is already reused in [`git-mark-all-resolved`](https://github.com/unixorn/git-extra-commands/blob/cc3d4f2d3a8718bfa7bf902ae296f31ebca50a5c/bin/git-mark-all-reso …

Make `git-edit-conflicts` specific to conflicts

---

README.md

Add zsh plugin link to replace the stock omz one

Add zsh plugin link to replace the stock omz one

---

README.md
bin/git-prune-branches
bin/git-remote-default-branch

Many repositories have switched from using 'master' to a less potentially offensive name like 'main' for their primary branch.
* Update `git-prune-branches` to not assume the default branch is named master.
* Add `git-remote-default-branch` to make it easy to find the default branch name.

Not all repos have master as their default branch.

---

README.md

This one's from a [tweet by @jnesselr](https://twitter.com/jnesselr/status/1334586152691625985).

Add another method for finding a remote's default branch.

---

bin/git-changelog

`git-changelog` was breaking on systems where `python` is `python3`, so update the shebang to use `python2` explicitly.
Closes #143

Make git-changelog explicitly use python2 in shebang

---

README.md

Currently the steps don't show how to install the plugin to a custom oh-my-zsh installation folder
Changed from `cd` to the folder to cloning directly in to the custom/default folder.

Update oh-my-zsh steps to make it easier for installation, and to use custom folder

---

README.md
bin/git-fzf-add
bin/git-fzf-log-browser
bin/git-fzf-pickaxe-browser
bin/git-fzf-reflog-browser

- Add links to [Fuzzy Finding in Bash with fzf](https://bluz71.github.io/2018/11/26/fuzzy-finding-in-bash-with-fzf.html) and [The Git Pickaxe](http://www.philandstuff.com/2014/02/09/git-pickaxe.html) articles
- Add `git-fzf-add`, `git-fzf-log-browser`, `git-fzf-pickaxe-browser` and `git-fzf-reflog-browser` helper scripts.

Add fzf helper scripts and article links

---

README.md
bin/git-authors
bin/git-changes

- Fix typo in README.md
- Rename `git-changes` to `git-authors` to better reflect what it actually does. Add a `git-changes` symlink for backwards compatibility.

Rename git-changes to git-authors

---

README.md
bin/git-checkout-default-branch
bin/git-origin-head

I got tired of trying to remember which branch repositories use as their default - `main`, `master`, whatever.
Adds `git-origin-head` and `git-checkout-default-branch` scripts

Add commands to print or checkout origin's default branch

---

README.md

git-cop is now git-lint.
https://github.com/bkuhlmann/git-lint/commit/c21a42c82036365f855fe2064ebd0c5126550ab3
https://github.com/bkuhlmann/git-lint/commit/b3396de6901b54139ba775c35155ea3310304b69

scripts: git-cop -> git-lint

---

bin/git-children-of

Add missing `git-children-of` script

Forgot to add the actual git-children-of script

---

.github/workflows/awesomebot.yml

Sometimes valid links return 5xx codes during `awesomebot` checks, causing a false failure during PR checks.
Ignore them, if something really goes offline it'll 404 eventually.

Update awesomebot to ignore some 5xx results

---

README.md
bin/git-amend-all
bin/git-branch-status
bin/git-checkout-branches
bin/git-merged-branches
bin/git-remove-conflicts

Add more scripts from `git-amend-all` | John Wiegley's [git scripts](https://github.com/jwiegley/git-scripts)

More from jwiegley collection

---

bin/git-fzf-log-browser

Snipped too much template when creating this script and left out the `has` function.

Add missing `has` function to `git-fzf-log-browser`

---

README.md
bin/git-where-pr

`git-where-pr` opens the Pull Request on GitHub where a commit originated

Add Mislav's `git-where-pr` script

---

README.md

Markdown parser didn't like having a | inside a `code` block

Deal with Markdown parser error in README.md

---

.github/workflows/mega-linter.yml
README.md
bin/git-upstream-name

Add helper script `git-upstream-name` that prints the upstream of the current branch

Add `git-upstream-name`

---

README.md

Not all repos use `master` as the default branch any more, so add an alias to `.gitconfig` to find the current repo's default branch and switch to it.

Add `checkout-default` alias info

---

bin/git-fzf-pickaxe-browser
bin/git-fzf-reflog-browser

Two additional `git-fzf-*` scripts were missing the `has` function. (See #210).

Add missing `has` function to `git-fzf-{pickaxe,reflog}-browser`

---

bin/git-branch-rebaser

The script currently supports only master. Other commands were updated to support multiple default branches, update this one the same.
Signed-off-by: Tomer Arbel Eliyahu <tomer.b.eliyahu@intel.com>

bugfix: git-branch-rebaser support any default branch

---

bin/git-when-merged

Makes git-when-merged work with Python 3
1. As said in the Pre-requisites Python 3+ is required.
2. Python 2 [got retired](https://www.python.org/doc/sunset-python-2/).
3. Currently git-when-merged does not work on a system w/o Python 2
These changes make the script compatible with Python 3.
Tested against `Python 3.10.9`

Update git-when-merged to Python3

---

.github/workflows/mega-linter.yml
README.md

https://gist.github.com/grawity/4392747 is 404, remove

Remove link to @grawity's 404 gist

---

bin/git-attic
bin/git-flush
bin/git-open-jira
bin/git-prune-branches
bin/git-purge-from-history
bin/git-remove-conflicts
bin/git-replace-author
bin/git-up
bin/git-up-old

- Mark `bin/git-open-jira` as executable (only file in `bin/` that wasn't marked as such)
- Fix quoting `$0` issues
- Handle `PULL_ARGS` as an array (fixes whitespace/quoting issues)
- Change one shebang from `#!/bin/sh` to `#!/usr/bin/env bash` because it used `set -o pipefail`, which isn't in POSIX (Bashism)

fix: Quoting, array, and compatability bugs

---

README.md
bin/git-checkout-by-date
bin/git-history-graph
bin/git-replace-author
bin/git-undo

I found the original sources for 4 commands found in `git-extra-commands`.

Add original source for four scripts

---

bin/git-incoming
bin/git-outgoing

`cut -d"/" -f3` will break branches of the form
'dependabot/pip/platformdirs-4.1.0'. Since we only need to cut 'refs/heads' part, select all strings starting with third when cutting

Fix git-incoming/git-outgoing

---

.github/PULL_REQUEST_TEMPLATE.md
README.md

Remove gitready.com link, it's not resolving

gitready.com is not resolving.

---

README.md

Add _How Does Git Work?_ article

Add _How Does Git Work?_ article

---

README.md

Add a link to blog post about using git log for function tracing

Add function tracing blog post

---

README.md

Fix format of `git-open-jira` entry

Fix `git-open-jira`

---

README.md

Add link to git config article

Add link to git config article

---

bin/git-semvers

Add Daniel Hoherd's `git-semvers`

Add `git-semvers`

---

README.md

Add link to Scott Chacon's blog post about how to tweak your `git` configuration to make life easier.

Add link to Scott Chacon's git config post

---

.github/workflows/awesomebot.yml

Some sites forbid scraping from GitHub IPs, so treat a permission error for a page as it being present, otherwise we'd be getting a 404.

Ignore 403 errors
